### PR TITLE
This disables taskbar-autohide for  meilix custom ISO - (Solves- #108) 

### LINKED ISSUE #108: Disabling autohide-taskbar on startup for Meilix
**I'm submitting a ...**
- [ ] bug report
- [x] enhancement request
- [ ] new theme/module request

### Short description

Disabling the taskbar auto-hide feature on startup by default for Meilix ISO,
This option is for the user to enable the autohide feature using the meilix-generator webapp.

### PR DESCRIPTION
**Pull request by pranav1698**
Fixes #108 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Added brief description with screenshots.

#### Changes proposed in this pull request:

- Setting `hidable=true` to false in panel configuration file

Thank you!

### CODE REVIEW

**Review by pranav1698 — COMMENTED** [review]
@tabesin @abishekvashok @meets2tarun please review

**Review by pranav1698 — COMMENTED** [review]
@tabesin please review

**Review by tabesin — APPROVED** [review]

**Comment by xeon-zolt** [comment]
I still have question how it affects the change ?

**Comment by pranav1698** [comment]
It does not affect anythisng,
This is just because this should be disabled by default
and, according to the generator user should have the choice of enabling or
disabling the taskbar-autohide feature

**Comment by xeon-zolt** [comment]
yea I get that but according to this https://github.com/fossasia/meilix-generator/issues/111 
hiding should be enabled by default in release iso

**Pull request merged**
